project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Computational linguisics and linguistic theories - Spring 2023"
  description: "Homepage for LING8505 - CLLT course at NTU University, Spring 2023."
  site-url: "https://lopentu.github.io/cllt/"

  repo-url: https://github.com/lopen/cllt
  repo-actions: [edit, issue]

  open-graph: true



  page-footer:
    right: "網頁用 [Quarto](https://quarto.org/) 設計"
    left: "&copy; Copyright 2023, Shu-Kai Hsieh"
    background: "#D9E3E4"

  sidebar:
    background: "#036D19"
    logo: "images/logo.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/lopentu
        text: "GitHub organization"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "課程資訊"
        contents:
          - href: course-overview.qmd
            text: 導覽
          - href: course-syllabus.qmd
            text: 課綱
          - href: course-team.qmd
            text: 助教
          - href: index.qmd
            text: 時程
          - href: course-links.qmd
            text: 連接

      - section: "計算環境"
        contents:
          - href: computing-env.qmd
            text: 計算工具與作業繳交說明

      - section: "期末專題"
        contents:
          - href: project-description.qmd
            text: 專題計劃需知

      - section: "每週教材"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
         
      - section: "補充說明"
        # contents:
        #   - href: supplemental/slr-derivations.qmd
        #     text: SLR derivations
        #   - href: supplemental/model-diagnostics-matrix.qmd
        #     text: Model diagnostics
        #   - href: supplemental/mlr-matrix.qmd
        #     text: MLR matrix notation
        #   - href: supplemental/log-transformations.qmd
        #     text: Log transformations
        #   - href: supplemental/model-selection-criteria.qmd
        #     text: Model selection criteria

format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
      # light: [cosmo, theme.scss]
      # dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual