project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Computational linguisics and linguistic theories - Spring 2023"
  description: "Homepage for LING8505 - CLLT course at NTU University, Spring 2023."
  site-url: "https://lopentu.github.io/cllt2023/"

  repo-url: https://github.com/lopentu/cllt2023
  repo-actions: [edit, issue]

  open-graph: true



  page-footer:
    right: "網頁用 [Quarto](https://quarto.org/) 設計"
    left: "&copy; Copyright 2023, Shu-Kai Hsieh"
    background: "#D9E3E4"

  sidebar:
    background: "#036D19"
    logo: "images/logo.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/lopentu
        text: "GitHub organization"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "課程資訊"
        contents:
          - href: course-overview.qmd
            text: 導覽
          - href: course-syllabus.qmd
            text: 課綱
          - href: course-team.qmd
            text: 助教
          - href: index.qmd
            text: 時程
          - href: course-links.qmd
            text: 連結

      - text: "計算環境與作業繳交方式"
        href: computing-env.qmd

      - text: "期末專題計劃需知"
        href: project-description.qmd

      - section: "每週教材"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week3.qmd
            text: "Week 3"
          - href: weeks/week4.qmd
            text: "Week 4"
          - href: weeks/week5.qmd
            text: "Week 5"
      - section: "補充說明"
        # contents:
        #   - href: supplemental/slr-derivations.qmd
        #     text: SLR derivations
        #   - href: supplemental/model-diagnostics-matrix.qmd
        #     text: Model diagnostics
        #   - href: supplemental/mlr-matrix.qmd
        #     text: MLR matrix notation
        #   - href: supplemental/log-transformations.qmd
        #     text: Log transformations
        #   - href: supplemental/model-selection-criteria.qmd
        #     text: Model selection criteria

format:
  html:
    highlight-style: a11y
    # theme:
      # light: flatly>
      # dark: darkly
      # light: [cosmo, theme.scss]
      # dark: [cosmo, theme-dark.scss]
    # mainfont: "Atkinson Hyperlegible"
    theme: [yeti,my_styles.scss]
    # css: styles.css
    css: [styles.css, sydney-fonts.css]
    mainfont: Nunito 
    code-copy: true
    code-overflow: wrap
    toc: true

from: markdown+emoji
freeze: auto

# editor: visual