---
title: "計算語言學與語言學理論"
tbl-colwidths: [5,8,8,8,8,8,8,8,8,8]
---

::: column-screen-inset-right
|           週次            | 日期  | 主題                    |                                                                              預習 📖                                                                              |              投影片               |                       助教課                        |                                                 課堂練習                                                 |                                                                     作業                                                                     |
|:-----:|-------|-------|:-----------------------:|:-----:|:-----:|:-----:|:-----:|
|  [1](/weeks/week-1.html)  | 02/23 | 課程導論                |                                                                                                                                                                   | [orientation](/weeks/week-1.html) |                                                     |                                                                                                          |                                                                                                                                              |
|  [2](/weeks/week-2.html)  | 03/02 | 計算語言學導論          |                                                                                                                                                                   |      [w2](/weeks/week2.html)      |           [slides](/labs/Week2_spaCy.pdf)           | [colab](https://colab.research.google.com/drive/1EJ7_Gc4M6xlf5lmDz4og-Y1qw56i5eDv#scrollTo=2bgNFiH0hbch) | [HW1](https://classroom.github.com/a/dSlccwZi),[HW1_Ans](https://drive.google.com/file/d/1z_Fo3o223I-QPO8Kh86kWrREHy2Q2pmy/view?usp=sharing) |
|  [3](/weeks/week3.html)   | 03/09 | 計算構詞與詞彙 (1)      |                                                     [slp3-02](https://web.stanford.edu/~jurafsky/slp3/2.pdf)                                                      |      [w3](/weeks/week3.html)      | [slides](/labs/Week3_%EF%BC%B7ord_Segmentation.pdf) | [colab](https://colab.research.google.com/drive/1Oj_BsykCk4J7R9xYO2HJa7WTuwb04679#scrollTo=iSE-OZ0cCiR5) |  [HW2](https://classroom.github.com/a/nxTCYAiT)                                                                                                                                            |
|  [4](/weeks/week-4.html)  | 03/16 | 計算構詞與詞彙 (2)      |                                                     [slp3-23](https://web.stanford.edu/~jurafsky/slp3/23.pdf)                                                     |      [w4](/weeks/week4.html)      |                                                     | [colab](https://colab.research.google.com/drive/1zZoQJThyTQ3nhaRacduQADe65BKRABeM#scrollTo=2TSEGJJ3VH9L)                                                                                                         |  [HW3](https://classroom.github.com/a/jVgzCvnw)                                                                                                                                            |
|  [5](/weeks/week-5.html)  | 03/23 | 計算構詞與詞彙 (3)      |                                                     [slp3-21](https://web.stanford.edu/~jurafsky/slp3/21.pdf)                         |   [w5](/weeks/week5.html)                                    |   [guidline](/labs/Week5_annotation_guideline.pdf)                                                  |  [colab](https://colab.research.google.com/drive/1swk4bXnxaKcCLMhTTaWfLNFlMEjJBA9y), [gsheet](https://docs.google.com/spreadsheets/d/1VRfZ-1amB4-6D1-usWHM3TlvSoPs76fa9buQm6riyyc/edit?usp=share_link)                                                                                                        |                                                                                                                                              |
|  [6](/weeks/week-6.html)  | 03/30 | 計算構詞與詞彙 (4)      |                                               [slp3-25](Lexicons%20for%20Sentiment,%20Affect,%20and%20Connotation)                                                |                                   |                                                     |                                                                                                          |                                                                                                                                              |
|  [7](/weeks/week-7.html)  | 04/06 | 句法理論與剖析器        | [slp3-18](https://web.stanford.edu/~jurafsky/slp3/D.pdfhttps://web.stanford.edu/~jurafsky/slp3/18.pdf); [(Linzen and Baroni, 2021)](/supplemental/linzen2020.pdf) |                                   |                                                     |                                                                                                          |                                                                                                                                              |
|  [8](/weeks/week-8.html)  | 04/13 | 認知語法與計算          |                [cognitive linguistics meets computational linguistics](https://www.degruyter.com/document/doi/10.1515/9783110687279/html#contents)                |                                   |                                                     |                                                                                                          |                                                                                                                                              |
|  [9](/weeks/week-9.html)  | 04/20 | 語意表徵 (1)            |                                                     [slp3-06](https://web.stanford.edu/~jurafsky/slp3/6.pdf)                                                      |                                   |                                                     |                                                                                                          |                                                                                                                                              |
| [10](/weeks/week-10.html) | 04/27 | 語意表徵 (2)            |                                                     [slp3-10](https://web.stanford.edu/~jurafsky/slp3/10.pdf)                                                     |                                   |                                                     |                                                                                                          |                                                                                                                                              |
| [11](/weeks/week-11.html) | 05/04 | 語意表徵 (3) & 業師分享 |                                                     [slp3-11](https://web.stanford.edu/~jurafsky/slp3/11.pdf)                                                     |                                   |                                                     |                                                                                                          |                                                                                                                                              |
| [12](/weeks/week-12.html) | 05/11 | 語意表徵 (4)            |                                                     [slp3-22](https://web.stanford.edu/~jurafsky/slp3/22.pdf)                                                     |                                   |                                                     |                                                                                                          |                                                                                                                                              |
| [13](/weeks/week-13.html) | 05/18 | Bakeoff practice        |                                                                                                                                                                   |                                   |                                                     |                                                                                                          |                                                                                                                                              |
| [14](/weeks/week-14.html) | 05/25 | 語音、多模態與言談分析  |                       [slp3-15](https://web.stanford.edu/~jurafsky/slp3/15.pdf); [slp3-28](https://web.stanford.edu/~jurafsky/slp3/28.pdf)                        |                                   |                                                     |                                                                                                          |                                                                                                                                              |
| [15](/weeks/week-15.html) | 06/01 | 綜合討論                |                                                                                                                                                                   |                                   |                                                     |                                                                                                          |                                                                                                                                              |
| [16](/weeks/week-16.html) | 06/08 | 期末報告                |                                                                                                                                                                   |                                   |                                                     |                                                                                                          |                                                                                                                                              |
|                           |       |                         |                                                                                                                                                                   |                                   |                                                     |                                                                                                          |                                                                                                                                              |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|-----|-----|-----|:---:|:---:|:---:|:---------------------------:|:---:|:---:|:---:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
